#!/usr/bin/env sh

echo "- Removing dist directory"
rm -r dist
echo "- Copying public to dist"
cp -r public dist

cd dist

echo "- Vulcanizing..."
vulcanize -s -o index.html index.html
vulcanize -s -o editor.html editor.html
vulcanize -s -o viewer.html viewer.html
vulcanize -s -o docs.html docs.html

cd ..